name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: publish to gcloud
      uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@master
      with:
        image: gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}
        service: ${{ secrets.SERVICE_NAME }}
        credentials: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
      
