name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    

    - name: Deploy service to Cloud Run
      uses: stefda/action-cloud-run@v1.0
      with:
        image: gcr.io/${{ secrets.PROJECT_ID }}/jpstudy
        service: ${{ secrets.SERVICE_NAME }}
        project: ${{ secrets.PROJECT_ID }}
        region: europe-west4
        service key: ${{ secrets.GCLOUD_AUTH }}
