name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Set variables for tests
      run: dotnet user-secrets set "FirebaseConfig:ProjectId" "${{ secrets.PROJECT_ID }}" --project ./JapaneseGraph.Tests/JapaneseGraph.Tests.csproj
      
    - name: Set variables for migrations 
      run: dotnet user-secrets set "FirebaseConfig:ProjectId" "${{ secrets.PROJECT_ID }}" --project ./JapaneseGraphDataLoader/JapaneseGraphDataLoader.csproj
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build
      run: |
        docker build -t gcr.io/${{ secrets.PROJECT_ID }}/jpstudy:latest .

    - name: Push
      run: |
        docker push gcr.io/${{ secrets.PROJECT_ID }}/jpstudy:latest

    - name: Deploy
      run: |
        gcloud run deploy jpstudy \
        --region europe-west2 \
        --image gcr.io/${{ secrets.PROJECT_ID }}/jpstudy \
        --platform managed \
        --allow-unauthenticated \
        --project ${{ secrets.PROJECT_ID }}

